stages:
  - build
  - deploy
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building Next.js"
    - docker compose build
    - docker compose push
  tags:
    - production
  only:
    - main
deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd /var/www/unirem
    - echo "Pulling images..."
    - docker compose pull
    - docker compose up -d
  only:
    - main
  environment:
    name: production
    url: https://$DOMAIN
  tags:
    - production
